'use strict';Registry.require(["helper","convert"],()=>{const n=Registry.get("helper"),l=Registry.get("convert");let p;const A=a=>a&&"http"==a.substr(0,4),E="internal user-agent accept-charset accept-encoding access-control-request-headers access-control-request-method connection content-length cookie cookie2 date dnt expect host keep-alive origin referer te trailer transfer-encoding upgrade via".split(" "),B=a=>E.includes(a)||0===a.indexOf("proxy-")||0===a.indexOf("sec-"),F={"cache-control":"no-cache",
pragma:"no-cache"},G={"cache-control":"max-age=0, must-revalidate"},q=a=>({responseXML:"",responseText:"",response:null,readyState:4,responseHeaders:"",status:0,statusText:"",error:a||"Forbidden"}),v=a=>{if("Blob"===a.type)return new Blob([l.str2arrbuf(a.value)]);if("File"===a.type)return new File([l.str2arrbuf(a.value)],a.name,{type:a.meta,lastModified:a.lastModified||Date.now()});if("FormData"==a.type){const e=new FormData;Object.keys(a.value).forEach(g=>{const c="Array"===a.value[g].type,k=v(a.value[g]),
h=c?k:[k];h.forEach((a,b)=>{e.append(g,h[b])})});return e}if("Array"===a.type||"Object"===a.type){let e,g,c;"Object"===a?(c=Object.keys(a.value),g=a=>a<c.length?c[a]:null,e={}):(g=c=>c<a.value.length?c:null,e=[]);for(let c,h=0;null!==(c=g(h));h++)e[c]=v(a.value[c]);return e}return a.value},r=a=>{const e={};a&&a.split("\n").forEach(a=>{if(a=a.match(/^([^:]+): ?(.*)/)){const c=a[1].toLowerCase();e[c]=(void 0!==e[c]?", ":"")+(a[2]||"").replace(/,/g,"%2C")}});return e},H=a=>{a=a.split(";").filter(a=>
"string"===typeof a&&!!a.trim());var e=a.shift().split("=");const g=e.shift();e=e.join("=");const c={name:g,value:decodeURIComponent(e)};a.forEach(function(a){var e=a.split("=");a=e.shift().trimLeft().toLowerCase();e=e.join("=");"expires"===a?(a=new Date(decodeURIComponent(e)),isNaN(a.getTime())||(c.expires=a)):"max-age"===a?c.maxAge=parseInt(e,10):"secure"===a?c.secure=!0:"httponly"===a?c.httpOnly=!0:"samesite"===a?c.sameSite=e:c[a]=e});return c},I=(a,e,g)=>{void 0===g&&(g={});const c=n.assign({},
e||{}),k=(a,b)=>{if(c[a])c[a]("function"==typeof b?b():b)};e=(a,b)=>{c[a]&&(k(a,b),c[a]=null)};if(g.internal||A(a.url)){var h=window.fetch&&a.url&&"http"==a.url.substr(0,4),l=!p.mozAnon&&a.anonymous,b=a.fetch;return h&&(l||b)?C(a,c,g,e,k):y(a,c,g,e,k)}console.warn("xhr: invalid scheme of url:",a.url);a=q("Invalid scheme");e("onerror",a);e("ondone",a)},z="tm-finalurl"+rea.runtime.short_id.toLowerCase(),D="tm-setcookie"+rea.runtime.short_id.toLowerCase();var C=(a,e,g,c,k)=>{const h=a=>{const b=[];let c,
d;a.headers&&(c=a.headers.get(z)||a.url,a.headers.forEach((a,d)=>{d=d.toLowerCase();[z,D].includes(d)||b.push(d+":"+a)}),(d=a.headers.get(D))&&b.push("set-cookie:"+d));return{readyState:4,responseHeaders:b.join("\n"),finalUrl:c,status:a.status,statusText:a.statusText}},n=b=>{((a,b)=>{const d=[];for(let w=0,c=a.length;w<c;w+=b)d.push(a.slice(w,b+w));return d})(b,parseInt(a.partialSize)).forEach(a=>{k("onpartial",{partial:a})})};try{var b={};b.method=a.method||"GET";b.redirect="follow";if(a.nocache||
a.revalidate)b.cache="no-store";b.credentials=a.anonymous?"omit":"include";if(a.headers){const c={};Object.keys(a.headers).forEach(b=>{let e=b,d=a.headers[b];if(p.prefix)B(b.toLowerCase())&&(e=p.prefix+b,d=null===d?"":l.encodeS(d));else if(null===d)return;c[e]=d});b.headers=new window.Headers(c)}void 0!==a.timeout&&(b.timeout=a.timeout);void 0!==a.data&&(b.body="typified"===a.data_type?v(a.data):"string"===typeof a.data?a.data:JSON.stringify(a.data));var m=window.fetch(a.url,b).then(b=>{const f=h(b);
(0!==f.status||200>f.status||300<=f.status)&&0<a.retries?(a.retries--,C(a,e,g,c,k)):(()=>{let c;if(b.ok)void 0!==a.responseType?(()=>{let d;const c=a.responseType?a.responseType.toLowerCase():"";if(a.convertBinary){if("document"==c)return d=r(f.responseHeaders)["content-type"]||"text/html",new window.Promise(a=>b.text().then(b=>{a({document:b,contentType:d})}));if("json"==c)return b.text();if("arraybuffer"==c||"blob"==c)return b.arrayBuffer().then(a=>l.arrbuf2str(a))}else{if("arraybuffer"==a.responseType)return b.arrayBuffer();
if("blob"==a.responseType)return b.blob();if("document"==a.responseType)return d=r(f.responseHeaders)["content-type"]||"text/xml",(new window.DOMParser).parseFromString(b.text(),d);if("json"==a.responseType)return JSON.parse(b.text());console.warn("xhr: responseType",a.responseType," is not implemented!");return b.text()}})().then(a=>{f.response=a;c()}):void 0!==a.overrideMimeType&&window.TextDecoder?b.arrayBuffer().then(d=>{const b=a.overrideMimeType.toLowerCase().match(/charset=([^;]+)/)[1];f.response=
(new window.TextDecoder(b)).decode(d);c()}):b.text().then(a=>{f.response=a;c()});else return f.responseXML=null,f.responseText="",f.response=null,{done:function(a){a()}};return{done:function(a){c=a}}})().done(()=>{if(a.partialSize&&e.onpartial){const b=a.convertBinary&&f.response?f.response:f.responseText;["response","responseText","responseXML"].forEach(a=>{delete f[a]});b&&(b.length>a.partialSize?n(b):f.response_data=b)}c("onload",f);c("ondone",f)})}).catch(a=>{a=h({status:408,statusText:a.message||
"Request Timeout"});c("onerror",a);c("ondone",a)})}catch(t){console.error(t.stack),b=q(t.message),c("onerror",b),c("ondone",b)}return{abort:function(){try{m.abort&&m.abort()}catch(t){}}}},y=(a,e,g,c,k)=>{let h,x;const b=new XMLHttpRequest(a.anonymous?{mozAnon:!0}:{}),m=d=>{var c="";let e=a.url;if(2<=b.readyState){if(c=b.getAllResponseHeaders())c=c.replace(/tm-finalurl[0-9a-zA-Z]*: .*[\r\n]{1,2}/i,""),c=c.replace(/tm-setcookie[0-9a-zA-Z]*:/i,"set-cookie:");let a;if(a=b.getResponseHeader(z)||b.responseURL)e=
a}c={readyState:b.readyState,responseHeaders:c,finalUrl:e,status:2<=b.readyState?b.status:0,statusText:2<=b.readyState?b.statusText:""};d&&4==b.readyState?(b.responseType?(c.responseXML=null,c.responseText=null,c.responseType=b.responseType):(c.responseXML=b.responseXML,c.responseText=b.responseText),c.response=b.response):(c.responseXML=null,c.responseText="",c.response=null);return c},t=d=>{((a,d)=>{const b=[];for(let c=0,e=a.length;c<e;c+=d)b.push(a.slice(c,d+c));return b})(d,parseInt(a.partialSize)).forEach(a=>
{k("onpartial",{partial:a})})},f={onload:function(){const d=m(!0);(0!==d.status||200>d.status||300<=d.status)&&0<a.retries?(a.retries--,y(a,e,g,c,k)):(()=>{if(a.convertBinary&&d.response){var b=d.responseType?d.responseType.toLowerCase():"";h&&b!==h&&console.warn("xhr: requested responseType "+h+" differs from received "+b);if("document"==b||"document"==h)if("string"==typeof d.response)b=r(d.responseHeaders)["content-type"]||"text/html",d.response={document:d.response,contentType:b};else{b=d.response;
const a=b.contentType||"text/html";try{d.response={document:(new XMLSerializer).serializeToString(b.documentElement),contentType:a}}catch(J){const c="unable to serialize content type "+a;console.warn("xhr: ",c,b);d.response={error:c,contentType:a}}}else if("json"==b)d.response=JSON.stringify(d.response);else{if("blob"==b){let a;const b=new FileReader;b.onload=()=>{d.response=l.arrbuf2str(b.result);a()};b.readAsArrayBuffer(d.response);return{done:function(b){a=b}}}"arraybuffer"==b&&(d.response=l.arrbuf2str(d.response))}}return{done:function(a){a()}}})().done(()=>
{if(a.partialSize&&e.onpartial){const b=a.convertBinary&&d.response?d.response:d.responseText;["response","responseText","responseXML"].forEach(a=>{delete d[a]});b&&(b.length>a.partialSize?t(b):d.response_data=b)}c("onload",d);4==d.readyState&&c("ondone",d)})},onerror:function(){const b=m();4==b.readyState&&200!=b.status&&0!=b.status&&0<a.retries?(a.retries--,y(a,e,g,c,k)):(c("onerror",b),c("ondone",b))},onloadstart:function(){k("onloadstart",()=>m())},onreadystatechange:function(){k("onreadystatechange",
()=>m())},onprogress:function(a){k("onprogress",()=>{const c=m();var d=c;void 0===d&&(d={});try{let e=null,f=null;if(a.lengthComputable||0<a.total)e=a.loaded,f=a.total;else{const d=!b.responseType||["","text"].includes(b.responseType)?b.responseText:null;let g=Number(r(c.responseHeaders)["content-length"]||"");const h=2<c.readyState&&d?d.length:0;0==g&&(g=-1);e=a.loaded||h;f=a.total||g}d.lengthComputable=a.lengthComputable;d.loaded=e;d.done=e;d.position=e;d.total=f;d.totalSize=f}catch(J){}return d})},
ontimeout:function(){const a=m();c("ontimeout");c("ondone",a)},onabort:function(){const a=q("aborted");c("ondone",a)}};var u=0==Object.keys(f).concat(["ondone"]).filter(a=>!!e[a]).length;if(u)throw Error("Synchronous XHR is not supported anymore");Object.keys(f).forEach(a=>{if(e[a]||["ontimeout","onload","onerror","onabort"].includes(a))b[a]=f[a]});try{if(!g.internal&&!A(a.url))throw Error("Invalid scheme of url: "+a.url);b.open(a.method||"GET",a.url,!u,a.user,a.password);if(a.headers||a.nocache||
a.revalidate){const c={};a.headers&&n.assign(c,a.headers);a.nocache?n.assign(c,F):a.revalidate&&n.assign(c,G);Object.keys(c).forEach(a=>{let d=a,e=c[a];if(p.prefix)B(a.toLowerCase())&&(d=p.prefix+a,e=null===e?"":l.encodeS(e));else if(null===e)return;try{b.setRequestHeader(d,e)}catch(K){console.warn("xhr: rejected header",d,c[a])}})}void 0!==a.overrideMimeType&&b.overrideMimeType(a.overrideMimeType);void 0!==a.responseType&&(h=a.responseType.toLowerCase(),["document","json"].includes(h)||(b.responseType=
h));void 0!==a.timeout&&(b.timeout=a.timeout);void 0!==a.data?("typified"===a.data_type?b.send(v(a.data)):"string"===typeof a.data?b.send(a.data):b.send(JSON.stringify(a.data)),e.onprogress&&b.upload&&(b.upload.onprogress=f.onprogress)):b.send()}catch(d){console.error(d.stack),u=q(d.message),c("onerror",u),c("ondone",u)}x=x||{};return n.copy({abort:function(){b.abort()}},x)};Registry.register("xmlhttprequest","289e8b91",()=>({run:I,setConfig:function(a){p=a},getConfig:function(){return p},
makeErrorResponse:q,parseCookie:H,parseHeaders:r}))});
